### ISSUE TITLE
iOS Ad Bug

### ISSUE THREAD

**Issue by rothn** [danqing/2048#19]
After playing for a few seconds on an iPhone 6, an ad comes up that blocks the whole screen with an image extending off the screen and no button to close it.

**Comment by danqing** [comment]
You are playing with a "pirated" version of this game. The author likely copied my code and added ads. My version is ad-free.

**Comment by rothn** [comment]
How do I find the original?

**Comment by danqing** [comment]
The original is currently not on App Store, but you can download this repo and build directly to your phone.

**Comment by rothn** [comment]
If I pay the developer tax that is :). Thanks for the info!

**Comment by danqing** [comment]
That's not the case anymore - with Xcode 7 and later you don't need the $99 membership to build an app on your phone.
